name: Node.js CI
permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes controller
        run: npm run test-controller

      - name: Rodar testes external
        run: |
          npm start &
          sleep 5
          npm run test-external
          kill $SERVER_PID